/** @format */

import Link from 'next/link';
import './globals.css';
import {Inter} from 'next/font/google';

const inter = Inter({subsets: ['latin']});

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({children}) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<div className='flex gap-4 p-3 bg-slate-500 text-white'>
					<Link href='/'>홈으로</Link>
					<Link href='/login'>로그인 페이지</Link>
				</div>
				{children}
			</body>
		</html>
	);
}
